var str = "GeeksterPlatofrom";
var arr = [10, 20, 30];

console.log(str.startsWith("a"));
console.log(str.endsWith("m"));
console.log(str.length);
console.log(str.indexOf("s"));
console.log(str.lastIndexOf("e"));
console.log(str.includes("t"));
console.log(str.slice(2, 4));
console.log(str.replace("e", "a"));
console.log(str.substring(0, 4));
console.log(str.includes("e"));
console.log(str.charAt(4));
console.log(str.toUpperCase());
console.log(str.toLowerCase());
console.log(str.fontcolor("red"));
var s = "        hi    ";
console.log(s);
console.log(s.trim());
console.log(s.repeat(4));
